/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CrosshairsOpsFrame.java
 *
 * Created on Jul 23, 2010, 2:11:41 PM
 */
package ptscharts;

import java.util.List;

/**
 *
 * @author rickcharon
 */
public class PtsCrosshairsOpsFrame extends javax.swing.JFrame {

  PtsChartPanel chartPanel;

  /** Creates new form CrosshairsOpsFrame */
  public PtsCrosshairsOpsFrame(PtsChartPanel chartPanelIn) {
    chartPanel = chartPanelIn;
    initComponents();
  }

  public Object[] getRangeCrosshairs() {
    return (chartPanel.getCrosshair1().getRangeCrosshairs()).toArray();
  }

  public void refreshCrosshairLists() {
    horizontalList.setListData(chartPanel.getCrosshair1().getRangeCrosshairsValues());
    verticalList.setListData(chartPanel.getCrosshair1().getDomainCrosshairsValues());
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jScrollPane1 = new javax.swing.JScrollPane();
    horizontalList = new javax.swing.JList();
    addHorizontal = new javax.swing.JButton();
    addHorizontalText = new javax.swing.JTextField();
    deleteSelectedHorizontal1 = new javax.swing.JButton();
    jPanel2 = new javax.swing.JPanel();
    jScrollPane2 = new javax.swing.JScrollPane();
    verticalList = new javax.swing.JList();
    deleteSelectedVertical = new javax.swing.JButton();
    refreshLists = new javax.swing.JButton();

    jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Horizontal Crosshairs:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14))); // NOI18N

    horizontalList.setFont(new java.awt.Font("DejaVu Sans", 1, 14));
    jScrollPane1.setViewportView(horizontalList);

    addHorizontal.setFont(new java.awt.Font("DejaVu Sans", 1, 14));
    addHorizontal.setText("Add Horizontal");
    addHorizontal.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        addHorizontalActionPerformed(evt);
      }
    });

    addHorizontalText.setFont(new java.awt.Font("DejaVu Sans", 0, 18));
    addHorizontalText.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyTyped(java.awt.event.KeyEvent evt) {
        addHorizontalTextKeyTyped(evt);
      }
    });

    deleteSelectedHorizontal1.setFont(new java.awt.Font("DejaVu Sans", 1, 14));
    deleteSelectedHorizontal1.setText("Delete Selected");
    deleteSelectedHorizontal1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        deleteSelectedHorizontal1ActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(addHorizontal)
          .addComponent(deleteSelectedHorizontal1)
          .addComponent(addHorizontalText, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(49, 49, 49))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(deleteSelectedHorizontal1)
            .addGap(18, 18, 18)
            .addComponent(addHorizontal)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(addHorizontalText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Vertical Crosshairs:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14))); // NOI18N

    verticalList.setFont(new java.awt.Font("DejaVu Sans", 1, 14));
    jScrollPane2.setViewportView(verticalList);

    deleteSelectedVertical.setFont(new java.awt.Font("DejaVu Sans", 1, 14));
    deleteSelectedVertical.setText("Delete Selected");

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(deleteSelectedVertical)
        .addGap(7, 7, 7))
    );
    jPanel2Layout.setVerticalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(deleteSelectedVertical)
          .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE))
        .addContainerGap())
    );

    refreshLists.setFont(new java.awt.Font("DejaVu Sans", 1, 14));
    refreshLists.setText("Refresh Lists");
    refreshLists.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        refreshListsActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(layout.createSequentialGroup()
            .addGap(306, 306, 306)
            .addComponent(refreshLists)))
        .addContainerGap(29, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addComponent(refreshLists)
        .addContainerGap(44, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void addHorizontalTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addHorizontalTextKeyTyped
    //System.out.println(evt.);
    evt.getKeyChar();
    evt.getKeyCode();
    char a = 2;
    Character cin = new Character(evt.getKeyChar());
    if (!(Character.isDigit(evt.getKeyChar()) || evt.getKeyChar() == '.')) {
      evt.consume();
      System.err.println("Only digits or decimal point allowed! addHorizontalTextKeyTyped()");
    }
  }//GEN-LAST:event_addHorizontalTextKeyTyped

  private void refreshListsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshListsActionPerformed
    refreshCrosshairLists();
  }//GEN-LAST:event_refreshListsActionPerformed

  private void addHorizontalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addHorizontalActionPerformed
    Double newHCH = Double.parseDouble(addHorizontalText.getText());
    chartPanel.setupHorizontalCrosshair(newHCH);
  }//GEN-LAST:event_addHorizontalActionPerformed

  private void deleteSelectedHorizontal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteSelectedHorizontal1ActionPerformed
    Object[] selVals = horizontalList.getSelectedValues();
    String[] remStrs = new String[selVals.length];
    for (int i = 0; i < selVals.length; i++) {
      remStrs[i] = selVals[i].toString();
    }
    chartPanel.getCrosshair1().removeRangeCrosshairs(remStrs);
  }//GEN-LAST:event_deleteSelectedHorizontal1ActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(new Runnable() {

      public void run() {
        new PtsCrosshairsOpsFrame(null).setVisible(true);
      }
    });
  }
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton addHorizontal;
  private javax.swing.JTextField addHorizontalText;
  private javax.swing.JButton deleteSelectedHorizontal1;
  private javax.swing.JButton deleteSelectedVertical;
  private javax.swing.JList horizontalList;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JButton refreshLists;
  private javax.swing.JList verticalList;
  // End of variables declaration//GEN-END:variables
}
